name: Pypy update

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Build and publish Cohpy package to Pypi. (${{ matrix.python-version }})
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build